spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/arh?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 0913

  mvc:
    path match:
      matching-strategy: ant_path_matcher


  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        use_sql_comments: true
        show_sql: true
        format_sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
  profiles:
    include: oauth


logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
jwt:  #waveofmymind-spring-boot-for-jwt-algorithm-review-board-project-waveofmymind-spring-boot-for-jwt-algorithm-review-board-projectv
  secret: d2F2ZW9mbXltaW5kLXNwcmluZy1ib290LWZvci1qd3QtYWxnb3JpdGhtLXJldmlldy1ib2FyZC1wcm9qZWN0LXdhdmVvZm15bWluZC1zcHJpbmctYm9vdC1mb3Itand0LWFsZ29yaXRobS1yZXZpZXctYm9hcmQtcHJvamVjdA==

springdoc:
  swagger-ui:
    enabled: true #// swagger ui 사용여부 (굳이 설정하지 않아도 default는 true)
  version: 'v1' // API 문서 버전
  default-consumes-media-type: application/json // 기본 consume media type
  default-produces-media-type: application/json // 기본 produce media type
  model-and-view-allowed: true #// ModelAndView 허용